const fs = require('fs');
let html = fs.readFileSync('app.html', 'utf8');

// ─── 1. Reorder sections: Day first, then Morning, then Night ───
html = html.replace(
  `  let html='';\n  html+=\`<div class="dp-section">☀️ Morning</div>\`;\n  plan.morning.forEach((block,bi)=>{ html+=renderDpBlock('morning',bi,block); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('morning')">+ Add morning block</button>\`;\n  html+=\`<div class="dp-section">⚡ During the day</div>\`;\n  plan.day.forEach((block,bi)=>{ html+=renderDpBlock('day',bi,block); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('day')">+ Add task</button>\`;\n  html+=\`<div class="dp-section">🌙 Night</div>\`;\n  plan.night.forEach((block,bi)=>{ html+=renderDpBlock('night',bi,block); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('night')">+ Add night block</button>\`;`,
  `  let html='';\n  html+=\`<div class="dp-section">⚡ During the day</div>\`;\n  plan.day.forEach((block,bi)=>{ html+=renderDpBlock('day',bi,block,plan.day.length); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('day')">+ Add task</button>\`;\n  html+=\`<div class="dp-section">☀️ Morning</div>\`;\n  plan.morning.forEach((block,bi)=>{ html+=renderDpBlock('morning',bi,block,plan.morning.length); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('morning')">+ Add morning block</button>\`;\n  html+=\`<div class="dp-section">🌙 Night</div>\`;\n  plan.night.forEach((block,bi)=>{ html+=renderDpBlock('night',bi,block,plan.night.length); });\n  html+=\`<button class="dp-add-block" onclick="dpAddBlock('night')">+ Add night block</button>\`;`
);

// ─── 2. Replace renderDpBlock to include up/down buttons + total param ───
html = html.replace(
  `function renderDpBlock(section,bi,block){\n  const steps=block.items||[];\n  return \`<div class="dp-block" id="dpblock-\${section}-\${bi}">\n    <div class="dp-block-head">\n      <input class="dp-block-title" value="\${(block.title||'').replace(/"/g,'&quot;')}" placeholder="Block title"\n        onchange="dpSaveTitle('\${section}',\${bi},this.value)"/>\n      <button class="dp-del-block" onclick="dpDelBlock('\${section}',\${bi})">✕</button>\n    </div>\n    \${steps.map((s,si)=>\`\n      <div class="dp-step-row">\n        <span class="dp-step-dash">—</span>\n        <input class="dp-step-input" value="\${(s||'').replace(/"/g,'&quot;')}" placeholder="Step..."\n          onchange="dpSaveStep('\${section}',\${bi},\${si},this.value)"/>\n        <button class="dp-del-step" onclick="dpDelStep('\${section}',\${bi},\${si})">✕</button>\n      </div>\`).join('')}\n    <button class="dp-add-step" onclick="dpAddStep('\${section}',\${bi})">+ Add step</button>\n  </div>\`;\n}`,
  `function renderDpBlock(section,bi,block,total){\n  const steps=block.items||[];\n  const len=total||_dayPlans[_activePlanDay][section].length;\n  return \`<div class="dp-block" id="dpblock-\${section}-\${bi}">\n    <div class="dp-block-head">\n      <div class="dp-block-reorder">\n        <button class="dp-reorder-btn" onclick="dpMoveBlock('\${section}',\${bi},-1)" \${bi===0?'disabled':''} title="Move up">↑</button>\n        <button class="dp-reorder-btn" onclick="dpMoveBlock('\${section}',\${bi},1)" \${bi===len-1?'disabled':''} title="Move down">↓</button>\n      </div>\n      <input class="dp-block-title" value="\${(block.title||'').replace(/"/g,'&quot;')}" placeholder="Block title"\n        onchange="dpSaveTitle('\${section}',\${bi},this.value)"/>\n      <button class="dp-del-block" onclick="dpDelBlock('\${section}',\${bi})">✕</button>\n    </div>\n    \${steps.map((s,si)=>\`\n      <div class="dp-step-row">\n        <span class="dp-step-dash">—</span>\n        <input class="dp-step-input" value="\${(s||'').replace(/"/g,'&quot;')}" placeholder="Step..."\n          onchange="dpSaveStep('\${section}',\${bi},\${si},this.value)"/>\n        <button class="dp-del-step" onclick="dpDelStep('\${section}',\${bi},\${si})">✕</button>\n      </div>\`).join('')}\n    <button class="dp-add-step" onclick="dpAddStep('\${section}',\${bi})">+ Add step</button>\n  </div>\`;\n}\n\nfunction dpMoveBlock(section,bi,dir){\n  const arr=_dayPlans[_activePlanDay][section];\n  const newIdx=bi+dir;\n  if(newIdx<0||newIdx>=arr.length)return;\n  const tmp=arr[bi]; arr[bi]=arr[newIdx]; arr[newIdx]=tmp;\n  saveDayPlans();\n  renderDayPlanner();\n}`
);

// ─── 3. Add CSS for reorder buttons ───
html = html.replace(
  `.dp-del-block{background:none;border:none;color:var(--t4);font-size:13px;cursor:pointer;padding:2px 6px;border-radius:4px;transition:color .15s;}`,
  `.dp-block-reorder{display:flex;gap:2px;flex-shrink:0;}\n.dp-reorder-btn{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.08);border-radius:5px;color:var(--t2);font-size:12px;width:24px;height:24px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .15s;padding:0;line-height:1;}\n.dp-reorder-btn:hover:not([disabled]){background:rgba(255,200,0,0.1);border-color:rgba(255,200,0,0.25);color:var(--y);}\n.dp-reorder-btn[disabled]{opacity:.2;cursor:not-allowed;}\n.dp-del-block{background:none;border:none;color:var(--t4);font-size:13px;cursor:pointer;padding:2px 6px;border-radius:4px;transition:color .15s;}`
);

if(!html.includes('dpMoveBlock')) { console.error('FAIL: dpMoveBlock not found'); process.exit(1); }
if(!html.includes('dp-reorder-btn')) { console.error('FAIL: CSS not found'); process.exit(1); }
fs.writeFileSync('app.html', html);
console.log('✓ Day planner patch done');
